### ISSUE TITLE
运行报错，不知道咋解决了，报错贴出来了

### ISSUE THREAD

**Issue by SSylow** [nftblackmagic/sdwebui-api-manager#5]
`*** API error: GET: http://***:7860/info {'error': 'KeyError', 'detail': '', 'body': '', 'errors': "'dataset'"}
    Traceback (most recent call last):
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 98, in receive
        return self.receive_nowait()
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/modules/api/api.py", line 152, in exception_handling
        return await call_next(request)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/modules/api/api.py", line 116, in log_and_time
        res: Response = await call_next(req)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
        raise exc
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
        raise e
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
        response = await func(request)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 271, in api_info
        return gradio.blocks.get_api_info(config, serialize)  # type: ignore
      File "/opt/source/sdwebui-api-manager/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 504, in get_api_info
        serializer = serializing.COMPONENT_MAPPING[type]()
    KeyError: 'dataset'

---`
我用的是腾讯云的
GPU计算型GN8 | GN8.LARGE56
Ubuntu Server 22.04 LTS 64位
找到了一个说降低gradio版本的 试了也不行

**Comment by SSylow** [comment]
这个访问能出界面，访问的时候才出错的。

**Comment by danblen** [comment]
你有解决吗？我pip安装的时候提示包有冲突，然后启动起来访问不了

**Comment by nftblackmagic** [comment]
Close by commit 2c4efd5

**Comment by nftblackmagic** [comment]
sd的一个插件报错了， 可以删掉这个插件 

rm -rf stable-diffusion-webui/extensions/sd-webui-depth-lib/
